version: "3.9"
services:

  client:
    image: research_beta_emulator_quic:latest
    #    build: .
    command: --config-file /run/config.json --run-dir /run ${target}
    depends_on:
      - server
    volumes:
      - ${runDir}:/run:rw
      - ${BASE_DIR}/certs/ssl_keylog.txt:/host/certs/ssl_keylog.txt:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PYTHONUNBUFFERED: 1
      SSLKEYLOGFILE: /host/certs/ssl_keylog.txt
    networks:
      - default
      - docker-elk_elk

  server:
    image: ${serverImage}
    cap_add:
      - NET_ADMIN
    environment:
      HOST_UID: ${UID}
    volumes:
      - ./dataset:/etc/nginx/html:ro
      - ${runDir}:/run:rw

networks:
  docker-elk_elk:
    external: true

  default:
    internal: true
    ipam:
      config:
        - subnet: 172.16.${NETWORK_ID}.0/24

