FROM nginx:1.21.1 AS build

WORKDIR /src

RUN apt-get update

RUN apt-get install -y git gcc make g++ cmake perl libunwind-dev golang && \
    git clone https://boringssl.googlesource.com/boringssl && \
    mkdir boringssl/build && \
    cd boringssl/build && \
    cmake .. && \
    make -j`nproc`

RUN apt-get install -y mercurial libperl-dev libpcre3-dev zlib1g-dev libxslt1-dev libgd-ocaml-dev libgeoip-dev && \
    hg clone https://hg.nginx.org/nginx-quic   && \
    hg clone http://hg.nginx.org/njs -r "0.6.2" && \
    cd nginx-quic && \
    hg update quic

COPY beta.diff /src/nginx-quic
# RUN cd nginx-quic && \
#     hg import -m "beta patch" beta.diff

RUN cd nginx-quic && \
    auto/configure `nginx -V 2>&1 | sed "s/ \-\-/ \\\ \n\t--/g" | grep "\-\-" | grep -ve opt= -e param= -e build=` \
                   --build=nginx-quic --with-debug \
                   --with-http_v3_module --with-stream_quic_module \
                   --with-cc-opt="-I/src/boringssl/include" --with-ld-opt="-L/src/boringssl/build/ssl -L/src/boringssl/build/crypto" && \
    make -j`nproc`

FROM nginx:1.21.1

RUN apt-get update && \
    apt install -y iproute2 procps tcpdump iptables

COPY --from=build /src/nginx-quic/objs/nginx //usr/sbin

CMD ["bash", "/etc/nginx/common/container-start.sh"]
