#!/usr/bin/env python3

import argparse
import json
import pathlib
import sys
from glob import glob
from typing import Dict, List

import numpy as np


def main():
    parser = argparse.ArgumentParser("Parse the playback reports generated by dash-emulator-quic")
    parser.add_argument("--folder", required=True, type=str, help="Folder containing all reports")
    parser.add_argument("--average-stall-dur", action="store_true", help="Print average stall durations")
    parser.add_argument("--average-stall-num", action="store_true", help="Print average stall numbers")
    parser.add_argument("--average-quality-switch-num", action="store_true",
                        help="Print the average number of quality switches")
    parser.add_argument("--std-stall-dur", action="store_true", help="Print the standard deviation of stall durations")
    parser.add_argument("--std-stall-num", action="store_true", help="Print the standard deviation of stall numbers")
    parser.add_argument("--std-quality-switch-num", action="store_true",
                        help="Print the standard deviation of number of quality switches")
    args = parser.parse_args()
    classified_reports = fetch_reports_from_folder(args.folder)
    print_header(args.average_stall_dur, args.average_stall_num, args.average_quality_switch_num, args.std_stall_dur,
                 args.std_stall_num, args.std_quality_switch_num)
    for video in sorted(classified_reports.keys()):
        files = classified_reports[video]
        PlaybackReportAnalyzer(video, files).analyze(args.average_stall_dur, args.average_stall_num,
                                                     args.average_quality_switch_num, args.std_stall_dur,
                                                     args.std_stall_num, args.std_quality_switch_num)


def print_header(average_stall_dur, average_stall_num, average_quality_switch_num, std_stall_dur, std_stall_num,
                 std_quality_switch_num):
    sys.stdout.write("%-20s" % "Video")
    if average_stall_dur:
        sys.stdout.write("%-20s" % "avg-stall-dur")
    if std_stall_dur:
        sys.stdout.write("%-20s" % "std-stall-dur")
    if average_stall_num:
        sys.stdout.write("%-20s" % "avg-stall-num")
    if std_stall_num:
        sys.stdout.write("%-20s" % "std-stall-num")
    if average_quality_switch_num:
        sys.stdout.write("%-20s" % "avg-quality-switch")
    if std_quality_switch_num:
        sys.stdout.write("%-20s" % "std-quality-switch")
    sys.stdout.write("\n")


def fetch_reports_from_folder(folder: str) -> Dict[str, List[str]]:
    files = glob(f"{folder}/*.json")
    classified_files = {}
    for file_path in files:
        filename = pathlib.Path(file_path).stem
        video, index = filename.rsplit('-', maxsplit=1)
        if video not in classified_files:
            classified_files[video] = []
        classified_files[video].append(file_path)
    return classified_files


class PlaybackReportAnalyzer:
    def __init__(self, video: str, reports: List[str]):
        self.video = video
        self.reports = reports
        self._reports_data = None

    def analyze(
            self,
            average_stall_dur=False,
            average_stall_num=False,
            average_quality_switch_num=False,
            std_stall_dur=False,
            std_stall_num=False,
            std_quality_switch_num=False
    ):
        self._reports_data = []
        for report in self.reports:
            with open(report) as f:
                self._reports_data.append(json.load(f))
        sys.stdout.write("%-20s" % self.video)

        avg_stall_dur_value, std_stall_dur_value = self._calculate_stall_dur()
        avg_stall_num_value, std_stall_num_value = self._calculate_stall_num()
        avg_switch_num_value, std_switch_num_value = self._calculate_quality_switch_num()

        if average_stall_dur:
            sys.stdout.write("%-20.2f" % avg_stall_dur_value)
        if std_stall_dur:
            sys.stdout.write("%-20.2f" % std_stall_dur_value)
        if average_stall_num:
            sys.stdout.write("%-20.2f" % avg_stall_num_value)
        if std_stall_num:
            sys.stdout.write("%-20.2f" % std_stall_num_value)
        if average_quality_switch_num:
            sys.stdout.write("%-20.2f" % avg_switch_num_value)
        if std_quality_switch_num:
            sys.stdout.write("%-20.2f" % std_switch_num_value)
        sys.stdout.write("\n")

    def _calculate_stall_dur(self):
        stall_durs = [data["dur_stall"] for data in self._reports_data]
        return np.average(stall_durs), np.std(stall_durs)

    def _calculate_stall_num(self):
        stall_nums = [data["num_stall"] for data in self._reports_data]
        return np.average(stall_nums), np.std(stall_nums)

    def _calculate_quality_switch_num(self):
        quality_switch_nums = [data["num_quality_switches"] for data in self._reports_data]
        return np.average(quality_switch_nums), np.std(quality_switch_nums)


if __name__ == '__main__':
    main()
