FROM ymuski/nginx-quic

RUN apt update
RUN apt install -y iproute2 procps
RUN apt install -y tcpdump

# RUN nginx -v
# RUN apt install -y git make gcc libssl1.1
# RUN mkdir /wireshark && cd /wireshark/ && \
#     git clone --depth=1 https://git.lekensteyn.nl/peter/wireshark-notes && \
#     cd wireshark-notes/src && \
#     make && \
#     install libsslkeylog.so /usr/local/lib/